
modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"

[[mods]] #mandatory
modId="snowpig" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Snow Pig" #mandatory
displayURL="https://www.curseforge.com/members/uraneptus/projects" #optional
logoFile="snowpig-banner.png" #optional
credits="Sounds by Luz#8017" #optional
authors="Uraneptus" #optional
description='''
'''

[[dependencies.snowpig]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.snowpig]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.snowpig]]
    modId="farmersdelight"
    mandatory=false
    versionRange="[0.4.5,)"
    ordering="AFTER"
    side="BOTH"

[modproperties.snowpig]
    catalogueImageIcon= "snowpig-icon.png"
